micronaut:
  application:
    name: protargitJavaMn
  server:
    port: 8092
    ssl:
      port: 8093
netty:
  default:
    allocator:
      max-order: 3

hardware:
  services:
    enable: false

serial:
  usb:
    enable: true
  bluetooth:
    enable: false
    comport: /dev/ttyS0

socket:
  enable: true
  port: 50000

websocket:
  enable: true
  url: ws://localhost:8086/


